<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit94ba82a31912125ff88a96edf0df842f
{
    public static $files = array (
        'f084d01b0a599f67676cffef638aa95b' => __DIR__ . '/..' . '/smarty/smarty/libs/bootstrap.php',
    );

    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Config' => __DIR__ . '/../..' . '/class/Config.class.php',
        'Functions' => __DIR__ . '/../..' . '/class/Functions.class.php',
        'Routes' => __DIR__ . '/../..' . '/class/Routes.class.php',
        'Template' => __DIR__ . '/../..' . '/class/Template.class.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit94ba82a31912125ff88a96edf0df842f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit94ba82a31912125ff88a96edf0df842f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit94ba82a31912125ff88a96edf0df842f::$classMap;

        }, null, ClassLoader::class);
    }
}
